Agrega funcionalidad de agrupar por parejas, trabajado con sergio (Y)
makeitrealcamp/top-v22 pull request #30
Opened 2022-04-28 00:38 UTC by nathanvr

feature worked with Sergio.

2022-05-01 21:58 UTC, juanan150 requested changes

2022-05-01 21:58 UTC, juanan150 commented on praxis/jonathanValencia.js
> +            console.log([nameRandom.pop(), nameRandom.pop()])
El código está imprimiendo el resultado en consola pero no lo está retornando. Por favor cambiarlo para que retorne todo el arreglo final con las parejas aleatorias en lugar de imprimirlo

2022-05-01 23:02 UTC, juanan150 approved these changes
Muy bien!

2022-05-10 21:31 UTC, SergioJaramilloL approved these changes

2022-05-10 21:31 UTC, merged